apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: litellm-credentials
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secret-store
    kind: ClusterSecretStore
  target:
    name: litellm-credentials
    creationPolicy: Owner
  data:
    - secretKey: base_url
      remoteRef:
        key: secrets/litellm/credentials
        property: base_url
    - secretKey: api_key
      remoteRef:
        key: secrets/litellm/credentials
        property: api_key
