apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: parasol-insurance
  namespace: {{ .Values.namespace }}
  labels:
    app: parasol-insurance
spec:
  to:
    kind: Service
    name: parasol-insurance
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
